- LICENSE.md
- LICENSES/APACHE-2.0.txt
- LICENSES/CC-BY-4.0.txt
See https://github.com/open-gitops/documents/issues/2
Ideally this PR should be merged before any other code or non-code.
Note other CNCF requires files are in the OpenGitOps Default Community Health Files repo https://github.com/open-gitops/.github
Signed-off-by: Scott Rigby <scott@r6by.com>
> Add licenses for non-code and any future code

- README.md
Just to get us started with the readme styles people seem to like
> Initial Readme in line with OGO repo style

- README.md
- gatsby-config.js
- package-lock.json
Couple of 404s on links such as twitter and reddit and a small patch to the readme if you're cool with that 🚀
> 🐇 FIX - Broken links to socials 🐇

- content/testimonials/testimonial-1.mdx
- content/testimonials/testimonial-2.mdx
- content/testimonials/testimonial-3.mdx
We have permission to use these quotes.
To-do: specify name for Curve quote. OK for now.
There are more coming.
Follow-up: #8
> 3 testimonials to start

- content/principles/automated-delivery.mdx
- content/principles/closed-loop.mdx
- content/principles/declarative-config.mdx
- content/principles/software-agents.mdx
- content/principles/version-controlled.mdx
Version 0.1.0 of the principles on the home page.
> Set principles to match basic documents

- .gitignore
- package.json
- public/CNAME
Signed-off-by: Dan Garfield <dan@todaywasawesome.com>
> Add deploy script, set CNAME for build purposes

- content/pages/about.mdx
> Fix charter link on about page

- content/pages/get-involved.mdx
https://github.com/open-gitops/project/discussions/33
> docs(get-involved.mdx): 1st & 3rd Wednesdays at 19:00 GMT

- content/events/gitopscon-eu-2022.mdx
- content/events/openshift-commons-gitopsday.mdx
Adding two upcoming events:
* GitOpsCon Europe 2022
* OpenShift Commons GitOps Day
Signed-off-by: Christian Hernandez <chernand@redhat.com>
> Adding Upcoming Events - OpenShift commons and GitOpsCon

- content/events/20220216-gitops-eks-anywhere-flux.mdx
@scottrigby - please let me know if I'm submitting this correctly. ;) 
Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>
> Create event GitOps with Amazon EKS Anywhere + Flux with Dan Budris

- content/pages/get-involved.mdx
https://github.com/open-gitops/project/discussions/new
Fix https://github.com/open-gitops/website/issues/6
Signed-off-by: lloydchang <lloydchang@gmail.com>
> docs(get-involved.mdx): add "Open a discussion"

- content/events/20220331-gitops-for-helm-users.mdx
Signed-off-by: Scott Rigby <scott@r6by.com>
> Add tomorrows event to calendar

- content/events/argocon-2022.mdx
Signed-off-by: Christian Hernandez <chernand@redhat.com>
> added argocon

- content/events/gitopsdays-2022.mdx
changing url to reflect gitops days 2022 youtube playlist instead of website - thanks!
Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>
> update gitops days url

- content/events/20220915-cncf-odw-Flux-OCI
Add past CNCF On-Demand Webinar: Flux increased security & scalability with OCI to event listing.
Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>
> Add 20220915-cncf-odw-Flux-OCI to events

- content/events/20220929-cncf-odw-how-to-gitops-your-terraform
Adding CNCF On-Demand Webinar: How to GitOps your Terraform! on 29 Sep. 2022
Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>
> create event for 20220929 cncf on-demand webinar

- src/components/header.js
Adding banner for Argo graduation.
Signed-off-by: Christian Hernandez <christian@chernand.io>
> adding Argo banner

- content/events/gitopscon-na-2023.mdx
- src/components/header.js
https://github.com/open-gitops/website/issues/114
> fix: update GitOpsCon North America recording

- content/events/gitopscon-eu-2023-virtual.mdx
We have to add the possibility for multiple day events in the future.
> chore: add GitOpsCon EU virtual edition

- content/events/argocon-eu-2024.mdx
- content/events/argocon-na-2024.mdx
- content/events/gitopscon-na-2024.mdx
ArgoCon and GitOpsCon got mangled in the last commit. This should fix all of them.
> Fix 2024 events

- content/pages/get-involved.mdx
https://cloud-native.slack.com/archives/C01G9DEE88M/p1713459494273759
> Replace the mention of #wg-gitops, an archived slack channel

- src/components/header.js
Updating the banner to an upcoming event.
> updating banner.

- src/components/header.js
Resolves https://github.com/open-gitops/website/issues/139
update header title with new event
> update header title with new event

- content/events/argocon-na-2024.mdx
- content/events/gitopscon-eu-2023-virtual.mdx
> chore: add ArgoCon23 & GitOpsCon EU 23 recordings

- content/events/argocon-eu-2025.mdx
- src/components/header.js
> KubeCon London event announce

- content/events/argocon-na-2025.mdx
- content/events/fluxcon-na-2025.mdx
- content/events/gitopscon-na-2025.mdx
hi friends
just adding the colo's for kubecon
see you there
> fluxcon/argocon/gitopscon NA 25
